default_stages: [commit]
repos:
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: forbid-binary
        exclude: .png
      # - id: shellcheck
  - repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.51.dss
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline', 'use-all-plugins']
        exclude: go.sum
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black